x1, y1 = derivative(x, y)
# plt.plot(x1, y1, label = 'Progonka')
# plt.xlabel('x')
# plt.ylabel("y'")
# plt.legend()
# plt.show()

# x2, y2 = derivative(x1, y1)
# y2 += - func(x2)
# plt.plot(x2, y2, label = 'Abs_error')
# plt.xlabel('x')
# plt.ylabel("y'-sin_x")
# plt.legend()
# plt.show()
